services:
  postcode-api:
    build: .
    container_name: postcode-api
    restart: unless-stopped
    ports:
      - "0.0.0.0:8005:7777"
    volumes:
      - type: bind
        source: /opt/postcode/geodata/bag.sqlite
        target: /opt/postcode/geodata/bag.sqlite
        read_only: true
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"